#!/usr/bin/env python3
"""Apply drivability C++ geometry prior to residual object labels.

The drivability route produces a binary PCD with color-coded point cells:

- red   => drivable ground/floor
- white => wall
- blue  => other obstacle/non-drivable

This script voxelizes that geometry prior and votes it onto residual object
points generated by `cluster_residual_points.py`. The output keeps residual
objects for review only when they are not confidently explained by the
geometry prior.
"""

from __future__ import annotations

import argparse
import json
import struct
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np


GEOM_UNKNOWN = 0
GEOM_GROUND = 1
GEOM_WALL = 2
GEOM_OTHER = 3

GEOM_NAMES = {
    GEOM_UNKNOWN: "unknown",
    GEOM_GROUND: "ground",
    GEOM_WALL: "wall",
    GEOM_OTHER: "other",
}


def read_pcd_xyzrgb(path: Path) -> tuple[np.ndarray, np.ndarray]:
    fields: list[str] = []
    sizes: list[int] = []
    types: list[str] = []
    counts: list[int] = []
    points = 0
    data_offset = 0
    with path.open("rb") as f:
        while True:
            line_raw = f.readline()
            if not line_raw:
                raise ValueError(f"PCD header missing DATA line: {path}")
            line = line_raw.decode("ascii", errors="ignore").strip()
            parts = line.split()
            if not parts:
                continue
            key = parts[0]
            if key == "FIELDS":
                fields = parts[1:]
            elif key == "SIZE":
                sizes = [int(x) for x in parts[1:]]
            elif key == "TYPE":
                types = parts[1:]
            elif key == "COUNT":
                counts = [int(x) for x in parts[1:]]
            elif key in ("WIDTH", "POINTS"):
                points = int(parts[1])
            elif key == "DATA":
                if parts[1] != "binary":
                    raise ValueError("Only binary PCD is supported.")
                data_offset = f.tell()
                break
        if not counts:
            counts = [1] * len(fields)
        offsets = {}
        step = 0
        for name, size, count in zip(fields, sizes, counts):
            offsets[name] = step
            step += size * count
        for required in ("x", "y", "z", "rgb"):
            if required not in offsets:
                raise ValueError(f"PCD missing field {required}: {path}")
        f.seek(data_offset)
        raw = f.read(points * step)
    buf = np.frombuffer(raw, dtype=np.uint8).reshape(points, step)
    xyz = np.empty((points, 3), dtype=np.float32)
    for i, name in enumerate(("x", "y", "z")):
        xyz[:, i] = np.frombuffer(
            buf[:, offsets[name]: offsets[name] + 4].copy().tobytes(), dtype="<f4"
        )
    rgb_float = np.frombuffer(buf[:, offsets["rgb"]: offsets["rgb"] + 4].copy().tobytes(), dtype="<f4")
    rgb_u32 = rgb_float.view("<u4")
    rgb = np.empty((points, 3), dtype=np.uint8)
    rgb[:, 0] = (rgb_u32 >> 16) & 255
    rgb[:, 1] = (rgb_u32 >> 8) & 255
    rgb[:, 2] = rgb_u32 & 255
    return xyz, rgb


def label_from_rgb(rgb: np.ndarray) -> np.ndarray:
    labels = np.full(len(rgb), GEOM_OTHER, dtype=np.uint8)
    red = (rgb[:, 0] > 200) & (rgb[:, 1] < 80) & (rgb[:, 2] < 80)
    white = (rgb[:, 0] > 200) & (rgb[:, 1] > 200) & (rgb[:, 2] > 200)
    labels[red] = GEOM_GROUND
    labels[white] = GEOM_WALL
    return labels


def read_ply_xyz_object(path: Path) -> tuple[np.ndarray, np.ndarray]:
    with path.open("rb") as f:
        fmt = "ascii"
        props = []
        prop_types = []
        vertex_count = 0
        in_vertex = False
        header_lines = 0
        while True:
            raw = f.readline()
            if not raw:
                raise ValueError(f"Invalid PLY header: {path}")
            header_lines += 1
            line = raw.decode("ascii", errors="ignore").strip()
            parts = line.split()
            if len(parts) >= 2 and parts[0] == "format":
                fmt = parts[1]
            elif len(parts) >= 3 and parts[0] == "element" and parts[1] == "vertex":
                vertex_count = int(parts[2])
                in_vertex = True
            elif len(parts) >= 2 and parts[0] == "element":
                in_vertex = False
            elif in_vertex and len(parts) >= 3 and parts[0] == "property":
                prop_types.append(parts[1])
                props.append(parts[-1])
            elif line == "end_header":
                break

    if fmt == "ascii":
        data = np.loadtxt(path, skiprows=header_lines, dtype=np.float32)
        if data.ndim == 1:
            data = data.reshape(1, -1)
        idx = {name: i for i, name in enumerate(props)}
        object_field = "object" if "object" in idx else "object_id"
        xyz = data[:, [idx["x"], idx["y"], idx["z"]]].astype(np.float32)
        object_ids = data[:, idx[object_field]].astype(np.uint32)
        return xyz, object_ids

    if fmt != "binary_little_endian":
        raise ValueError(f"Unsupported PLY format: {fmt}")
    type_map = {
        "float": "<f4", "float32": "<f4", "double": "<f8",
        "uchar": "u1", "uint8": "u1", "char": "i1", "int8": "i1",
        "ushort": "<u2", "uint16": "<u2", "short": "<i2", "int16": "<i2",
        "uint": "<u4", "uint32": "<u4", "int": "<i4", "int32": "<i4",
    }
    dtype = np.dtype([(name, type_map.get(ptype, "<f4")) for ptype, name in zip(prop_types, props)])
    with path.open("rb") as f:
        while f.readline().strip() != b"end_header":
            pass
        arr = np.frombuffer(f.read(vertex_count * dtype.itemsize), dtype=dtype, count=vertex_count)
    object_field = "object" if "object" in props else "object_id"
    xyz = np.column_stack([arr["x"], arr["y"], arr["z"]]).astype(np.float32)
    object_ids = arr[object_field].astype(np.uint32)
    return xyz, object_ids


def pack_keys(coords: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    mins = coords.min(axis=0).astype(np.int64) - 2
    shifted = coords.astype(np.int64) - mins
    maxs = shifted.max(axis=0).astype(np.int64) + 3
    if np.any(maxs >= 2_000_000):
        raise ValueError(f"Coordinate span too large for packed key: {maxs.tolist()}")
    keys = (shifted[:, 0] * maxs[1] + shifted[:, 1]) * maxs[2] + shifted[:, 2]
    return keys.astype(np.int64), np.array([mins[0], mins[1], mins[2], maxs[1], maxs[2]], dtype=np.int64)


def pack_query(coords: np.ndarray, spec: np.ndarray) -> np.ndarray:
    mins = spec[:3]
    mult_y = int(spec[3])
    mult_z = int(spec[4])
    shifted = coords.astype(np.int64) - mins
    return ((shifted[:, 0] * mult_y + shifted[:, 1]) * mult_z + shifted[:, 2]).astype(np.int64)


def build_prior_voxels(xyz: np.ndarray, labels: np.ndarray, voxel_size: float) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    coords = np.floor(xyz / voxel_size).astype(np.int32)
    keys, spec = pack_keys(coords)
    order = np.argsort(keys)
    sorted_keys = keys[order]
    sorted_labels = labels[order]
    unique_keys, start, counts = np.unique(sorted_keys, return_index=True, return_counts=True)
    out_labels = np.empty(len(unique_keys), dtype=np.uint8)
    # Labels are only 1..3; count by small slices to avoid a huge dense matrix.
    for i, (s, c) in enumerate(zip(start, counts)):
        hist = np.bincount(sorted_labels[s:s + c], minlength=4)
        # Prefer structural ground/wall over generic other when close.
        if hist[GEOM_GROUND] >= max(1, hist[GEOM_WALL], hist[GEOM_OTHER] * 0.75):
            out_labels[i] = GEOM_GROUND
        elif hist[GEOM_WALL] >= max(1, hist[GEOM_OTHER] * 0.75):
            out_labels[i] = GEOM_WALL
        else:
            out_labels[i] = GEOM_OTHER
    return unique_keys, out_labels, spec


def vote_points(points: np.ndarray, prior_keys: np.ndarray, prior_labels: np.ndarray, spec: np.ndarray, voxel_size: float, neighbor_radius: int) -> np.ndarray:
    coords0 = np.floor(points / voxel_size).astype(np.int32)
    votes = np.zeros((len(points), 4), dtype=np.uint16)
    offsets = [
        (dx, dy, dz)
        for dx in range(-neighbor_radius, neighbor_radius + 1)
        for dy in range(-neighbor_radius, neighbor_radius + 1)
        for dz in range(-neighbor_radius, neighbor_radius + 1)
    ]
    offsets.sort(key=lambda item: item[0] * item[0] + item[1] * item[1] + item[2] * item[2])
    for dx, dy, dz in offsets:
        coords = coords0 + np.array([dx, dy, dz], dtype=np.int32)
        keys = pack_query(coords, spec)
        pos = np.searchsorted(prior_keys, keys)
        hit = (pos < len(prior_keys)) & (prior_keys[np.clip(pos, 0, len(prior_keys) - 1)] == keys)
        if not np.any(hit):
            continue
        labels = prior_labels[pos[hit]]
        rows = np.where(hit)[0]
        np.add.at(votes, (rows, labels), 1)
    assigned = np.argmax(votes, axis=1).astype(np.uint8)
    assigned[votes.sum(axis=1) == 0] = GEOM_UNKNOWN
    return assigned


def pca_normal_and_planarity(points: np.ndarray) -> tuple[list[float], float, float]:
    if len(points) < 3:
        return [0.0, 0.0, 1.0], 0.0, 0.0
    centered = points.astype(np.float64) - points.mean(axis=0, keepdims=True)
    cov = (centered.T @ centered) / max(len(points) - 1, 1)
    vals, vecs = np.linalg.eigh(cov)
    order = np.argsort(vals)[::-1]
    vals = vals[order]
    vecs = vecs[:, order]
    normal = vecs[:, -1]
    if normal[2] < 0:
        normal = -normal
    thickness = float(np.sqrt(max(vals[-1], 0.0)))
    spread = float(np.sqrt(max(vals[0], 0.0)))
    planarity = float(1.0 - thickness / max(spread, 1e-6))
    return normal.astype(float).tolist(), thickness, planarity


def classify_object(obj: dict, counts: Counter, total: int, normal_z: float, thickness: float, planarity: float, args: argparse.Namespace) -> tuple[str, str, str]:
    ground_ratio = counts[GEOM_GROUND] / max(total, 1)
    wall_ratio = counts[GEOM_WALL] / max(total, 1)
    other_ratio = counts[GEOM_OTHER] / max(total, 1)
    point_count = int(obj.get("point_count", total))
    if "max_extent" in obj:
        max_extent = float(obj["max_extent"])
    else:
        bbox_min = obj.get("bbox_min", [0.0, 0.0, 0.0])
        bbox_max = obj.get("bbox_max", [0.0, 0.0, 0.0])
        max_extent = max(float(bbox_max[i]) - float(bbox_min[i]) for i in range(3))
    horizontal = abs(normal_z) >= args.ground_normal_z_min
    vertical = abs(normal_z) <= args.wall_normal_z_max
    planar = planarity >= args.planarity_min and thickness <= args.thickness_max
    clean_horizontal_surface = (
        abs(normal_z) >= args.geometry_ground_normal_z_min
        and planarity >= args.geometry_ground_planarity_min
        and thickness <= args.geometry_ground_thickness_max
    )

    if point_count >= args.min_absorb_points and ground_ratio >= args.ground_ratio and horizontal and planar:
        return "ground_surface_prior", "absorbed_by_drivability_ground", "drivability red vote + horizontal planar residual"
    if point_count >= args.min_absorb_points and wall_ratio >= args.wall_ratio and vertical and planar:
        return "wall_surface_prior", "absorbed_by_drivability_wall", "drivability white vote + vertical planar residual"
    if (
        point_count >= args.large_ground_min_points
        and ground_ratio >= args.large_ground_ratio
        and abs(normal_z) >= args.large_ground_normal_z_min
        and other_ratio <= args.large_ground_other_ratio_max
    ):
        return (
            "ground_surface_prior",
            "absorbed_by_drivability_ground_contaminated",
            "large horizontal residual with dominant drivability red vote; likely floor with edge clutter",
        )
    if (
        point_count >= args.geometry_ground_min_points
        and max_extent >= args.geometry_ground_min_extent
        and clean_horizontal_surface
        and wall_ratio <= args.geometry_ground_wall_ratio_max
        and other_ratio <= args.geometry_ground_other_ratio_max
    ):
        return (
            "ground_surface_prior",
            "absorbed_by_geometry_ground_unmatched",
            "clean large horizontal residual not covered by drivability prior",
        )
    if (
        point_count >= args.ground_fragment_min_points
        and ground_ratio >= args.ground_fragment_ratio
        and clean_horizontal_surface
    ):
        return (
            "ground_surface_prior",
            "absorbed_by_drivability_ground_fragment",
            "small clean horizontal fragment with dominant drivability red vote",
        )
    if point_count >= args.min_absorb_points and ground_ratio >= args.ground_ratio_loose and horizontal and thickness <= args.thickness_loose:
        return "ground_surface_prior", "absorbed_by_drivability_ground_loose", "loose drivability red vote + horizontal residual"
    if point_count >= args.min_absorb_points and wall_ratio >= args.wall_ratio_loose and vertical and thickness <= args.thickness_loose:
        return "wall_surface_prior", "absorbed_by_drivability_wall_loose", "loose drivability white vote + vertical residual"
    if other_ratio >= args.other_ratio:
        return obj.get("semantic_label", "unlabeled_residual"), "needs_semantic_review", "drivability blue/other or unmatched"
    return obj.get("semantic_label", "unlabeled_residual"), "needs_semantic_review", "insufficient geometry prior confidence"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--drivability-pcd", type=Path, required=True)
    parser.add_argument("--residual-ply", type=Path, required=True)
    parser.add_argument("--objects-jsonl", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--prior-voxel-size", type=float, default=0.10)
    parser.add_argument("--neighbor-radius", type=int, default=1)
    parser.add_argument("--ground-ratio", type=float, default=0.55)
    parser.add_argument("--wall-ratio", type=float, default=0.55)
    parser.add_argument("--ground-ratio-loose", type=float, default=0.40)
    parser.add_argument("--wall-ratio-loose", type=float, default=0.40)
    parser.add_argument("--other-ratio", type=float, default=0.60)
    parser.add_argument("--large-ground-ratio", type=float, default=0.65)
    parser.add_argument("--large-ground-normal-z-min", type=float, default=0.95)
    parser.add_argument("--large-ground-other-ratio-max", type=float, default=0.25)
    parser.add_argument("--large-ground-min-points", type=int, default=5000)
    parser.add_argument("--geometry-ground-min-points", type=int, default=1000)
    parser.add_argument("--geometry-ground-min-extent", type=float, default=3.0)
    parser.add_argument("--geometry-ground-normal-z-min", type=float, default=0.95)
    parser.add_argument("--geometry-ground-planarity-min", type=float, default=0.92)
    parser.add_argument("--geometry-ground-thickness-max", type=float, default=0.12)
    parser.add_argument("--geometry-ground-wall-ratio-max", type=float, default=0.10)
    parser.add_argument("--geometry-ground-other-ratio-max", type=float, default=0.35)
    parser.add_argument("--ground-fragment-min-points", type=int, default=50)
    parser.add_argument("--ground-fragment-ratio", type=float, default=0.85)
    parser.add_argument("--min-absorb-points", type=int, default=150)
    parser.add_argument("--ground-normal-z-min", type=float, default=0.82)
    parser.add_argument("--wall-normal-z-max", type=float, default=0.35)
    parser.add_argument("--planarity-min", type=float, default=0.90)
    parser.add_argument("--thickness-max", type=float, default=0.22)
    parser.add_argument("--thickness-loose", type=float, default=0.35)
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    prior_xyz, prior_rgb = read_pcd_xyzrgb(args.drivability_pcd)
    prior_labels = label_from_rgb(prior_rgb)
    prior_keys, prior_voxel_labels, spec = build_prior_voxels(prior_xyz, prior_labels, args.prior_voxel_size)

    residual_xyz, object_ids = read_ply_xyz_object(args.residual_ply)
    point_labels = vote_points(
        residual_xyz,
        prior_keys,
        prior_voxel_labels,
        spec,
        args.prior_voxel_size,
        args.neighbor_radius,
    )

    objects = {}
    with args.objects_jsonl.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            obj = json.loads(line)
            objects[int(obj["object_id"])] = obj

    by_object_indices: dict[int, list[int]] = defaultdict(list)
    for i, oid in enumerate(object_ids.tolist()):
        if oid:
            by_object_indices[int(oid)].append(i)

    output_jsonl = args.output_dir / "residual_objects_drivability_prior.jsonl"
    status_counts = Counter()
    status_points = Counter()
    label_counts = Counter()
    with output_jsonl.open("w", encoding="utf-8") as out:
        for oid in sorted(objects):
            obj = objects[oid]
            idx = np.array(by_object_indices.get(oid, []), dtype=np.int64)
            counts = Counter()
            if len(idx):
                counts.update(int(x) for x in point_labels[idx].tolist())
                pts = residual_xyz[idx]
                normal, thickness, planarity = pca_normal_and_planarity(pts)
            else:
                normal, thickness, planarity = [0.0, 0.0, 1.0], 0.0, 0.0
            total = int(sum(counts.values()))
            label, status, reason = classify_object(
                obj, counts, total, abs(float(normal[2])), thickness, planarity, args
            )
            obj = dict(obj)
            obj["semantic_label_original"] = obj.get("semantic_label", "")
            obj["semantic_label"] = label
            obj["status"] = status
            obj["drivability_prior_reason"] = reason
            obj["drivability_prior_counts"] = {GEOM_NAMES[k]: int(v) for k, v in sorted(counts.items())}
            obj["drivability_prior_ratios"] = {
                GEOM_NAMES[k]: (float(v) / max(total, 1)) for k, v in sorted(counts.items())
            }
            obj["pca_normal"] = normal
            obj["pca_normal_abs_z"] = abs(float(normal[2]))
            obj["pca_thickness_rms_recomputed"] = thickness
            obj["pca_planarity_recomputed"] = planarity
            out.write(json.dumps(obj, ensure_ascii=False) + "\n")
            status_counts[status] += 1
            status_points[status] += int(obj.get("point_count", total))
            label_counts[label] += 1

    report = {
        "drivability_pcd": str(args.drivability_pcd),
        "residual_ply": str(args.residual_ply),
        "objects_jsonl": str(args.objects_jsonl),
        "output_jsonl": str(output_jsonl),
        "prior_voxel_size": args.prior_voxel_size,
        "neighbor_radius": args.neighbor_radius,
        "prior_point_count": int(len(prior_xyz)),
        "prior_voxel_count": int(len(prior_keys)),
        "residual_point_count": int(len(residual_xyz)),
        "residual_object_count": int(len(objects)),
        "point_prior_counts": {GEOM_NAMES[k]: int(v) for k, v in sorted(Counter(point_labels.tolist()).items())},
        "status_counts": dict(status_counts),
        "status_points": dict(status_points),
        "semantic_label_counts": dict(label_counts),
    }
    report_path = args.output_dir / "drivability_prior_report.json"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
