#!/usr/bin/env python3
"""Build geometry patches with model-aware region growing.

This is the next step after build_geo_patch_graph.py.  The graph route decides
connected components from pairwise edges only, so A-B and B-C can merge A and C
even when C no longer fits the whole patch.  This script keeps the fast voxel
feature extraction and edge-admissibility pass, then grows each patch with a
dynamic patch model.

The decision is deliberately two-stage:

1. edge admissibility: local physical reachability, generated by the graph edge
   scorer.
2. patch membership: whether the candidate voxel still fits the patch model
   accumulated from already accepted voxels.
"""

from __future__ import annotations

import argparse
import json
import random
import subprocess
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

from build_geo_patch_demo import (
    compute_local_features,
    compute_local_features_torch,
    geometry_bucket,
    read_voxels,
)
from build_geo_patch_graph import (
    BUCKET_IDS,
    ID_BUCKETS,
    bucket_score_np,
    clamp01_np,
    collect_edges,
    voxel_arrays,
)


STABLE_SURFACE_BUCKETS = {BUCKET_IDS["horizontal"], BUCKET_IDS["vertical"]}
FINE_OBJECT_BUCKETS = {BUCKET_IDS["rough_mixed"], BUCKET_IDS["thin_linear"], BUCKET_IDS["unknown"]}
MAX_PATCH_PROTOTYPES = 24
PROTOTYPE_UPDATE_DISTANCE = 0.34
PROTOTYPE_CHART_UPDATE_PLANE_DISTANCE = 0.18
PROTOTYPE_CHART_UPDATE_NORMAL_ANGLE = 42.0


def normal_angle_deg_np(a: np.ndarray, b: np.ndarray) -> float:
    an = float(np.linalg.norm(a))
    bn = float(np.linalg.norm(b))
    if an < 1e-9 or bn < 1e-9:
        return 0.0
    cos = abs(float(np.dot(a, b) / (an * bn)))
    return float(np.degrees(np.arccos(np.clip(cos, -1.0, 1.0))))


def local_signature(arrays: dict[str, np.ndarray], index: int) -> np.ndarray:
    """Compact multimodal patch signature for prototype matching.

    The signature intentionally ignores absolute XYZ.  It describes local
    appearance and shape, so one patch may keep separate modes for flat ground,
    stair edges, shrub tops, and shrub sides without collapsing everything into
    a single mean.
    """

    normal = arrays["normal"][index]
    return np.asarray(
        [
            float(arrays["rgb"][index, 0]) / 255.0,
            float(arrays["rgb"][index, 1]) / 255.0,
            float(arrays["rgb"][index, 2]) / 255.0,
            float(arrays["roughness"][index]),
            float(arrays["planarity"][index]),
            float(arrays["linearity"][index]),
            min(float(arrays["local_color_std"][index]) / 128.0, 1.5),
            min(float(arrays["height_range"][index]) / 0.55, 1.5),
            abs(float(normal[2])),
        ],
        dtype=np.float64,
    )


def signature_distance(a: np.ndarray, b: np.ndarray) -> float:
    color = float(np.linalg.norm(a[:3] - b[:3]))
    shape = float(np.linalg.norm(a[3:8] - b[3:8]))
    normal_z = abs(float(a[8] - b[8]))
    return 0.46 * color + 0.42 * shape + 0.12 * normal_z


def frontier_chart_metrics(arrays: dict[str, np.ndarray], source_index: int, index: int, distance_scale: float) -> dict[str, float]:
    """Measure candidate continuity against the accepted frontier voxel.

    Region growth is a graph problem: a candidate is reached through one
    already accepted neighbor.  Stable surfaces therefore need both global
    patch consistency and local chart continuity.  This frontier chart keeps a
    long surface from being forced into one global plane while still requiring
    graph-local geometric agreement.
    """

    signature = local_signature(arrays, index)
    source_signature = local_signature(arrays, source_index)
    xyz = arrays["xyz"][index].astype(np.float64, copy=False)
    source_xyz = arrays["xyz"][source_index].astype(np.float64, copy=False)
    normal = arrays["normal"][index].astype(np.float64, copy=False)
    source_normal = arrays["normal"][source_index].astype(np.float64, copy=False)
    sig_distance = signature_distance(signature, source_signature)
    plane_residual = abs(float(np.dot(xyz - source_xyz, source_normal)))
    normal_angle = normal_angle_deg_np(source_normal, normal)
    dz = abs(float(xyz[2] - source_xyz[2]))
    combined = sig_distance
    combined += 0.28 * min(plane_residual / PROTOTYPE_CHART_UPDATE_PLANE_DISTANCE, 2.0)
    combined += 0.12 * min(normal_angle / max(PROTOTYPE_CHART_UPDATE_NORMAL_ANGLE, 1e-6), 2.0)
    return {
        "score": float(max(0.0, min(1.0, 1.0 - sig_distance / max(distance_scale, 1e-6)))),
        "plane_residual": plane_residual,
        "normal_angle": normal_angle,
        "dz": dz,
        "combined": combined,
    }


@dataclass
class PatchModel:
    """Incremental statistics used by model-aware growth."""

    seed_index: int
    seed_bucket: int
    count: int = 0
    xyz_sum: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))
    rgb_sum: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))
    normal_sum: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))
    roughness_sum: float = 0.0
    planarity_sum: float = 0.0
    linearity_sum: float = 0.0
    local_color_std_sum: float = 0.0
    height_range_sum: float = 0.0
    bucket_counts: Counter[int] = field(default_factory=Counter)
    xyz_min: np.ndarray = field(default_factory=lambda: np.full(3, np.inf, dtype=np.float64))
    xyz_max: np.ndarray = field(default_factory=lambda: np.full(3, -np.inf, dtype=np.float64))
    accepted_score_sum: float = 0.0
    rejected_reasons: Counter[str] = field(default_factory=Counter)
    prototypes: list[np.ndarray] = field(default_factory=list)
    prototype_counts: list[int] = field(default_factory=list)
    prototype_xyz: list[np.ndarray] = field(default_factory=list)
    prototype_normals: list[np.ndarray] = field(default_factory=list)

    def add(self, arrays: dict[str, np.ndarray], index: int, score: float = 1.0) -> None:
        xyz = arrays["xyz"][index].astype(np.float64, copy=False)
        rgb = arrays["rgb"][index].astype(np.float64, copy=False)
        normal = arrays["normal"][index].astype(np.float64, copy=True)
        current_normal = self.normal()
        if self.count > 0 and np.dot(normal, current_normal) < 0:
            normal = -normal
        self.count += 1
        self.xyz_sum += xyz
        self.rgb_sum += rgb
        self.normal_sum += normal
        self.roughness_sum += float(arrays["roughness"][index])
        self.planarity_sum += float(arrays["planarity"][index])
        self.linearity_sum += float(arrays["linearity"][index])
        self.local_color_std_sum += float(arrays["local_color_std"][index])
        self.height_range_sum += float(arrays["height_range"][index])
        self.bucket_counts[int(arrays["buckets"][index])] += 1
        self.xyz_min = np.minimum(self.xyz_min, xyz)
        self.xyz_max = np.maximum(self.xyz_max, xyz)
        self.accepted_score_sum += float(score)
        self.update_prototypes(arrays, index)

    def update_prototypes(self, arrays: dict[str, np.ndarray], index: int) -> None:
        signature = local_signature(arrays, index)
        xyz = arrays["xyz"][index].astype(np.float64, copy=False)
        normal = arrays["normal"][index].astype(np.float64, copy=True)
        norm = float(np.linalg.norm(normal))
        if norm > 1e-9:
            normal = normal / norm
        if not self.prototypes:
            self.prototypes.append(signature.copy())
            self.prototype_counts.append(1)
            self.prototype_xyz.append(xyz.copy())
            self.prototype_normals.append(normal.copy())
            return
        distances: list[float] = []
        for proto, proto_xyz, proto_normal in zip(self.prototypes, self.prototype_xyz, self.prototype_normals, strict=True):
            chart_plane = abs(float(np.dot(xyz - proto_xyz, proto_normal)))
            chart_angle = normal_angle_deg_np(proto_normal, normal)
            chart_penalty = 0.0
            if self.seed_bucket in STABLE_SURFACE_BUCKETS:
                chart_penalty += 0.35 * min(chart_plane / PROTOTYPE_CHART_UPDATE_PLANE_DISTANCE, 2.0)
                chart_penalty += 0.20 * min(chart_angle / max(PROTOTYPE_CHART_UPDATE_NORMAL_ANGLE, 1e-6), 2.0)
            distances.append(signature_distance(signature, proto) + chart_penalty)
        nearest = int(np.argmin(distances))
        nearest_plane = abs(float(np.dot(xyz - self.prototype_xyz[nearest], self.prototype_normals[nearest])))
        nearest_angle = normal_angle_deg_np(self.prototype_normals[nearest], normal)
        same_chart = (
            distances[nearest] <= PROTOTYPE_UPDATE_DISTANCE
            and (
                self.seed_bucket not in STABLE_SURFACE_BUCKETS
                or (
                    nearest_plane <= PROTOTYPE_CHART_UPDATE_PLANE_DISTANCE
                    and nearest_angle <= PROTOTYPE_CHART_UPDATE_NORMAL_ANGLE
                )
            )
        )
        if same_chart or len(self.prototypes) >= MAX_PATCH_PROTOTYPES:
            count = self.prototype_counts[nearest]
            alpha = 1.0 / float(count + 1)
            self.prototypes[nearest] = (1.0 - alpha) * self.prototypes[nearest] + alpha * signature
            self.prototype_xyz[nearest] = (1.0 - alpha) * self.prototype_xyz[nearest] + alpha * xyz
            proto_normal = self.prototype_normals[nearest]
            if np.dot(proto_normal, normal) < 0:
                normal = -normal
            updated_normal = (1.0 - alpha) * proto_normal + alpha * normal
            updated_norm = float(np.linalg.norm(updated_normal))
            if updated_norm > 1e-9:
                updated_normal = updated_normal / updated_norm
            self.prototype_normals[nearest] = updated_normal
            self.prototype_counts[nearest] = count + 1
        else:
            self.prototypes.append(signature.copy())
            self.prototype_counts.append(1)
            self.prototype_xyz.append(xyz.copy())
            self.prototype_normals.append(normal.copy())

    def prototype_score(self, arrays: dict[str, np.ndarray], index: int, distance_scale: float) -> float:
        if not self.prototypes:
            return 0.0
        signature = local_signature(arrays, index)
        min_distance = min(signature_distance(signature, proto) for proto in self.prototypes)
        return float(max(0.0, min(1.0, 1.0 - min_distance / max(distance_scale, 1e-6))))

    def chart_metrics(self, arrays: dict[str, np.ndarray], index: int, distance_scale: float) -> dict[str, float]:
        if not self.prototypes:
            return {"score": 0.0, "plane_residual": float("inf"), "normal_angle": 180.0, "dz": float("inf")}
        signature = local_signature(arrays, index)
        xyz = arrays["xyz"][index].astype(np.float64, copy=False)
        normal = arrays["normal"][index].astype(np.float64, copy=False)
        best: dict[str, float] | None = None
        best_distance = float("inf")
        for proto, proto_xyz, proto_normal in zip(self.prototypes, self.prototype_xyz, self.prototype_normals, strict=True):
            sig_distance = signature_distance(signature, proto)
            plane_residual = abs(float(np.dot(xyz - proto_xyz, proto_normal)))
            normal_angle = normal_angle_deg_np(proto_normal, normal)
            dz = abs(float(xyz[2] - proto_xyz[2]))
            combined = sig_distance
            combined += 0.28 * min(plane_residual / PROTOTYPE_CHART_UPDATE_PLANE_DISTANCE, 2.0)
            combined += 0.12 * min(normal_angle / max(PROTOTYPE_CHART_UPDATE_NORMAL_ANGLE, 1e-6), 2.0)
            if combined < best_distance:
                best_distance = combined
                best = {
                    "score": float(max(0.0, min(1.0, 1.0 - sig_distance / max(distance_scale, 1e-6)))),
                    "plane_residual": plane_residual,
                    "normal_angle": normal_angle,
                    "dz": dz,
                    "combined": combined,
                }
        assert best is not None
        return best

    def mean(self, key: str) -> float:
        return float(getattr(self, f"{key}_sum") / max(float(self.count), 1.0))

    def centroid(self) -> np.ndarray:
        return self.xyz_sum / max(float(self.count), 1.0)

    def color(self) -> np.ndarray:
        return self.rgb_sum / max(float(self.count), 1.0)

    def normal(self) -> np.ndarray:
        norm = float(np.linalg.norm(self.normal_sum))
        if norm < 1e-9:
            return np.array([0.0, 0.0, 1.0], dtype=np.float64)
        return self.normal_sum / norm

    def dominant_bucket(self) -> int:
        if not self.bucket_counts:
            return self.seed_bucket
        return int(self.bucket_counts.most_common(1)[0][0])

    def dominant_ratio(self) -> float:
        if not self.bucket_counts:
            return 1.0
        return float(self.bucket_counts.most_common(1)[0][1]) / max(float(self.count), 1.0)

    def extent(self) -> np.ndarray:
        return self.xyz_max - self.xyz_min

    def mean_score(self) -> float:
        return self.accepted_score_sum / max(float(self.count), 1.0)


def build_adjacency(n: int, src: np.ndarray, dst: np.ndarray) -> list[list[int]]:
    adjacency: list[list[int]] = [[] for _ in range(n)]
    for a, b in zip(src.tolist(), dst.tolist(), strict=True):
        adjacency[a].append(b)
        adjacency[b].append(a)
    return adjacency


def membership_score(
    arrays: dict[str, np.ndarray],
    model: PatchModel,
    index: int,
    args: argparse.Namespace,
    source_index: int | None = None,
) -> tuple[bool, float, str, dict[str, float]]:
    """Return whether a voxel fits the current patch model."""

    bucket = int(arrays["buckets"][index])
    dominant = model.dominant_bucket()
    centroid = model.centroid()
    patch_normal = model.normal()
    xyz = arrays["xyz"][index].astype(np.float64, copy=False)
    rgb = arrays["rgb"][index].astype(np.float64, copy=False)
    normal = arrays["normal"][index].astype(np.float64, copy=False)

    angle = normal_angle_deg_np(patch_normal, normal)
    rgb_dist = float(np.linalg.norm(model.color() - rgb))
    dz = abs(float(xyz[2] - centroid[2]))
    plane_residual = abs(float(np.dot(xyz - centroid, patch_normal)))
    rough_delta = abs(model.mean("roughness") - float(arrays["roughness"][index]))
    planarity_delta = abs(model.mean("planarity") - float(arrays["planarity"][index]))
    linearity_delta = abs(model.mean("linearity") - float(arrays["linearity"][index]))
    color_std_delta = abs(model.mean("local_color_std") - float(arrays["local_color_std"][index]))
    height_range_delta = abs(model.mean("height_range") - float(arrays["height_range"][index]))
    prototype_score = model.prototype_score(arrays, index, args.prototype_distance_scale)

    scores = {
        "color": float(clamp01_np(np.asarray([1.0 - rgb_dist / max(args.max_color_distance, 1e-6)]))[0]),
        "color_texture": float(clamp01_np(np.asarray([1.0 - color_std_delta / 85.0]))[0]),
        "roughness": float(clamp01_np(np.asarray([1.0 - rough_delta / 0.24]))[0]),
        "planarity": float(clamp01_np(np.asarray([1.0 - planarity_delta / 0.50]))[0]),
        "linearity": float(clamp01_np(np.asarray([1.0 - linearity_delta / 0.50]))[0]),
        "height_range": float(clamp01_np(np.asarray([1.0 - height_range_delta / 0.28]))[0]),
        "height": float(clamp01_np(np.asarray([1.0 - dz / max(args.max_height_delta * 2.8, 1e-6)]))[0]),
        "bucket": float(bucket_score_np(np.asarray([dominant], dtype=np.int16), np.asarray([bucket], dtype=np.int16))[0]),
        "normal": float(clamp01_np(np.asarray([1.0 - angle / max(args.max_normal_angle * 1.8, 1e-6)]))[0]),
        "plane": float(clamp01_np(np.asarray([1.0 - plane_residual / max(args.max_plane_residual * 2.5, 1e-6)]))[0]),
        "prototype": prototype_score,
        "chart": prototype_score,
        "chart_plane": 0.0,
        "chart_normal": 0.0,
        "chart_height": 0.0,
    }
    shape_score = (
        0.38 * scores["roughness"]
        + 0.24 * scores["linearity"]
        + 0.24 * scores["planarity"]
        + 0.14 * scores["height_range"]
    )
    texture_score = 0.62 * scores["color"] + 0.38 * scores["color_texture"]

    if dominant in STABLE_SURFACE_BUCKETS and model.dominant_ratio() >= args.stable_surface_ratio:
        surface_bridge = (
            args.enable_surface_multimodal_bridge
            and dominant == BUCKET_IDS["horizontal"]
            and bucket in {BUCKET_IDS["rough_mixed"], BUCKET_IDS["unknown"], BUCKET_IDS["thin_linear"]}
            and texture_score >= args.surface_bridge_texture_score
            and (shape_score >= args.surface_bridge_shape_score or scores["prototype"] >= args.surface_bridge_prototype_score)
        )
        if bucket not in {dominant, BUCKET_IDS["unknown"]} and not surface_bridge:
            return False, 0.0, "stable_bucket_mismatch", scores
        if rgb_dist > args.max_color_distance * 1.9 and color_std_delta > 55.0:
            return False, 0.0, "stable_color_texture_jump", scores
        normal_limit = min(args.max_normal_angle * 1.7, 88.0)
        global_normal_fail = angle > normal_limit
        global_plane_fail = plane_residual > args.max_plane_residual * args.stable_plane_factor
        global_height_fail = dominant == BUCKET_IDS["horizontal"] and dz > args.max_height_delta * args.stable_height_factor
        needs_chart = (global_normal_fail or global_plane_fail or global_height_fail) and not surface_bridge
        if needs_chart:
            chart = model.chart_metrics(arrays, index, args.prototype_distance_scale)
            if source_index is not None:
                source_bucket = int(arrays["buckets"][source_index])
                source_is_compatible_chart = source_bucket in {dominant, BUCKET_IDS["unknown"]}
                if source_is_compatible_chart:
                    frontier_chart = frontier_chart_metrics(arrays, source_index, index, args.prototype_distance_scale)
                    if frontier_chart["combined"] < chart["combined"]:
                        chart = frontier_chart
            scores["chart"] = chart["score"]
            scores["chart_plane"] = float(
                clamp01_np(np.asarray([1.0 - chart["plane_residual"] / max(args.max_plane_residual * 2.5, 1e-6)]))[0]
            )
            scores["chart_normal"] = float(
                clamp01_np(np.asarray([1.0 - chart["normal_angle"] / max(args.max_normal_angle * 1.8, 1e-6)]))[0]
            )
            scores["chart_height"] = float(clamp01_np(np.asarray([1.0 - chart["dz"] / max(args.max_height_delta * 2.8, 1e-6)]))[0])
            chart_normal_fail = chart["normal_angle"] > normal_limit
            chart_plane_fail = chart["plane_residual"] > args.max_plane_residual * args.stable_plane_factor
            chart_height_fail = dominant == BUCKET_IDS["horizontal"] and chart["dz"] > args.max_height_delta * args.stable_height_factor
            if chart_normal_fail:
                return False, 0.0, "stable_normal_jump", scores
            if chart_plane_fail:
                return False, 0.0, "stable_plane_residual", scores
            if chart_height_fail:
                return False, 0.0, "stable_height_jump", scores
        else:
            scores["chart"] = scores["prototype"]
            scores["chart_plane"] = scores["plane"]
            scores["chart_normal"] = scores["normal"]
            scores["chart_height"] = scores["height"]
        if surface_bridge:
            total = (
                0.52 * texture_score
                + 0.18 * shape_score
                + 0.12 * scores["chart"]
                + 0.10 * scores["bucket"]
                + 0.08 * scores["chart_height"]
            )
            threshold = args.min_surface_bridge_score
        else:
            total = (
                0.26 * scores["chart_plane"]
                + 0.22 * scores["chart_normal"]
                + 0.17 * texture_score
                + 0.13 * scores["chart"]
                + 0.12 * scores["bucket"]
                + 0.07 * shape_score
                + 0.03 * scores["chart_height"]
            )
            threshold = args.min_surface_membership_score
    else:
        if bucket not in FINE_OBJECT_BUCKETS and dominant in FINE_OBJECT_BUCKETS:
            return False, 0.0, "fine_to_stable_bucket_block", scores
        if rgb_dist > args.max_color_distance * args.object_color_factor and color_std_delta > args.object_texture_delta:
            return False, 0.0, "object_color_texture_jump", scores
        if rough_delta > args.object_roughness_delta and color_std_delta > args.object_texture_delta:
            return False, 0.0, "object_shape_texture_jump", scores
        # Do not hard-veto object-like patches by distance from the current
        # patch centroid in Z.  Tall shrubs, railings, stairs, and wall-attached
        # objects naturally grow away from their centroid.  Local height
        # continuity is already enforced by the edge-admissibility pass; here
        # height is only weak evidence in the membership score.
        if dominant == BUCKET_IDS["rough_mixed"]:
            total = (
                args.rough_texture_weight * texture_score
                + args.rough_shape_weight * shape_score
                + args.rough_prototype_weight * scores["prototype"]
                + args.rough_height_weight * scores["height"]
                + args.rough_bucket_weight * scores["bucket"]
                + args.rough_normal_weight * scores["normal"]
                + args.rough_plane_weight * scores["plane"]
            ) / max(
                args.rough_texture_weight
                + args.rough_shape_weight
                + args.rough_prototype_weight
                + args.rough_height_weight
                + args.rough_bucket_weight
                + args.rough_normal_weight
                + args.rough_plane_weight,
                1e-6,
            )
            threshold = args.min_rough_membership_score
        else:
            total = (
                args.object_texture_weight * texture_score
                + args.object_shape_weight * shape_score
                + args.object_prototype_weight * scores["prototype"]
                + args.object_height_weight * scores["height"]
                + args.object_bucket_weight * scores["bucket"]
                + args.object_normal_weight * scores["normal"]
                + args.object_plane_weight * scores["plane"]
            ) / max(
                args.object_texture_weight
                + args.object_shape_weight
                + args.object_prototype_weight
                + args.object_height_weight
                + args.object_bucket_weight
                + args.object_normal_weight
                + args.object_plane_weight,
                1e-6,
            )
            threshold = args.min_object_membership_score

    if total < threshold:
        return False, float(total), "membership_score_low", scores
    return True, float(total), "accepted", scores


def seed_order(arrays: dict[str, np.ndarray]) -> np.ndarray:
    stable = np.isin(arrays["buckets"], [BUCKET_IDS["horizontal"], BUCKET_IDS["vertical"]])
    # Stable surfaces first lock large planes before rough objects can bridge.
    return np.lexsort(
        (
            arrays["roughness"],
            -arrays["planarity"],
            ~stable,
        )
    )


def grow_region_model(
    arrays: dict[str, np.ndarray],
    adjacency: list[list[int]],
    args: argparse.Namespace,
) -> tuple[np.ndarray, list[dict[str, Any]]]:
    n = len(arrays["keys"])
    labels = np.full(n, -1, dtype=np.int32)
    patches: list[dict[str, Any]] = []
    next_patch_id = 1

    for seed in seed_order(arrays):
        seed_i = int(seed)
        if labels[seed_i] != -1:
            continue
        model = PatchModel(seed_index=seed_i, seed_bucket=int(arrays["buckets"][seed_i]))
        model.add(arrays, seed_i, 1.0)
        labels[seed_i] = next_patch_id
        queue: deque[int] = deque([seed_i])

        while queue:
            current = queue.popleft()
            for nbr in adjacency[current]:
                if labels[nbr] != -1:
                    continue
                ok, score, reason, _scores = membership_score(arrays, model, int(nbr), args, source_index=current)
                if not ok:
                    model.rejected_reasons[reason] += 1
                    continue
                labels[nbr] = next_patch_id
                model.add(arrays, int(nbr), score)
                queue.append(int(nbr))

        dominant_bucket = model.dominant_bucket()
        geometry_type = ID_BUCKETS[dominant_bucket] if model.dominant_ratio() >= 0.65 else "mixed"
        patches.append(
            {
                "patch_id": next_patch_id,
                "voxel_count": int(model.count),
                "status": "small_patch" if model.count < args.small_patch_voxels else "geo_patch",
                "geometry_type": geometry_type,
                "bucket_counts": {ID_BUCKETS[int(k)]: int(v) for k, v in model.bucket_counts.items()},
                "centroid": model.centroid().astype(float).tolist(),
                "bbox_3d": {"min": model.xyz_min.astype(float).tolist(), "max": model.xyz_max.astype(float).tolist()},
                "extent": model.extent().astype(float).tolist(),
                "mean_rgb": model.color().astype(float).tolist(),
                "mean_normal": model.normal().astype(float).tolist(),
                "mean_membership_score": float(model.mean_score()),
                "rejected_reasons_top": dict(model.rejected_reasons.most_common(8)),
            }
        )
        next_patch_id += 1

    if np.any(labels < 0):
        raise RuntimeError(f"internal error: unassigned voxels remain: {int(np.sum(labels < 0))}")
    return labels, patches


def summarize_patches_from_labels(
    arrays: dict[str, np.ndarray],
    labels: np.ndarray,
    args: argparse.Namespace,
) -> list[dict[str, Any]]:
    """Build viewer/report metadata from labels returned by a native backend."""

    if len(labels) == 0:
        return []
    order = np.argsort(labels, kind="stable")
    sorted_labels = labels[order]
    starts = np.r_[0, np.flatnonzero(np.diff(sorted_labels)) + 1]
    ends = np.r_[starts[1:], len(sorted_labels)]
    patch_ids = sorted_labels[starts].astype(np.int32, copy=False)
    counts = (ends - starts).astype(np.int64, copy=False)

    xyz_sorted = arrays["xyz"][order].astype(np.float64, copy=False)
    rgb_sorted = arrays["rgb"][order].astype(np.float64, copy=False)
    normals_sorted = arrays["normal"][order].astype(np.float64, copy=False)
    buckets_sorted = arrays["buckets"][order]

    xyz_sum = np.add.reduceat(xyz_sorted, starts, axis=0)
    rgb_sum = np.add.reduceat(rgb_sorted, starts, axis=0)
    normal_sum = np.add.reduceat(normals_sorted, starts, axis=0)
    xyz_min = np.minimum.reduceat(xyz_sorted, starts, axis=0)
    xyz_max = np.maximum.reduceat(xyz_sorted, starts, axis=0)
    centroids = xyz_sum / counts[:, None]
    mean_rgb = rgb_sum / counts[:, None]
    normal_norm = np.linalg.norm(normal_sum, axis=1)
    mean_normals = np.zeros_like(normal_sum)
    valid_normals = normal_norm > 1e-9
    mean_normals[valid_normals] = normal_sum[valid_normals] / normal_norm[valid_normals, None]

    patches: list[dict[str, Any]] = []
    for row_i, (patch_id, start, end, count) in enumerate(zip(patch_ids, starts, ends, counts, strict=True)):
        bucket_counts_raw = Counter(int(v) for v in buckets_sorted[start:end].tolist())
        dominant_bucket, dominant_count = bucket_counts_raw.most_common(1)[0]
        dominant_ratio = float(dominant_count) / max(float(count), 1.0)
        geometry_type = ID_BUCKETS[dominant_bucket] if dominant_ratio >= 0.65 else "mixed"
        patches.append(
            {
                "patch_id": int(patch_id),
                "voxel_count": int(count),
                "status": "small_patch" if int(count) < args.small_patch_voxels else "geo_patch",
                "geometry_type": geometry_type,
                "bucket_counts": {ID_BUCKETS[int(k)]: int(v) for k, v in bucket_counts_raw.items()},
                "centroid": centroids[row_i].astype(float).tolist(),
                "bbox_3d": {"min": xyz_min[row_i].astype(float).tolist(), "max": xyz_max[row_i].astype(float).tolist()},
                "extent": (xyz_max[row_i] - xyz_min[row_i]).astype(float).tolist(),
                "mean_rgb": mean_rgb[row_i].astype(float).tolist(),
                "mean_normal": mean_normals[row_i].astype(float).tolist(),
                "mean_membership_score": None,
                "rejected_reasons_top": {},
            }
        )
    return patches


def _write_cpp_region_input(path: Path, arrays: dict[str, np.ndarray], src: np.ndarray, dst: np.ndarray) -> None:
    n = np.asarray([len(arrays["xyz"])], dtype="<i8")
    m = np.asarray([len(src)], dtype="<i8")
    with path.open("wb") as f:
        f.write(b"GPRGv1\n")
        n.tofile(f)
        m.tofile(f)
        np.asarray(arrays["xyz"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["rgb"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["normal"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["roughness"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["planarity"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["linearity"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["local_color_std"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["height_range"], dtype="<f4", order="C").tofile(f)
        np.asarray(arrays["buckets"], dtype="<i2", order="C").tofile(f)
        np.asarray(src, dtype="<i4", order="C").tofile(f)
        np.asarray(dst, dtype="<i4", order="C").tofile(f)


def _read_cpp_region_labels(path: Path) -> np.ndarray:
    with path.open("rb") as f:
        magic = f.read(len(b"GPRGlabels1\n"))
        if magic != b"GPRGlabels1\n":
            raise RuntimeError(f"invalid C++ region-grower output magic: {magic!r}")
        n = np.fromfile(f, dtype="<i8", count=1)
        if len(n) != 1 or int(n[0]) <= 0:
            raise RuntimeError("invalid C++ region-grower output length")
        labels = np.fromfile(f, dtype="<i4", count=int(n[0]))
        if len(labels) != int(n[0]):
            raise RuntimeError("truncated C++ region-grower label output")
        return labels.astype(np.int32, copy=False)


def _cpp_flag_args(args: argparse.Namespace) -> list[str]:
    out: list[str] = []
    for name in [
        "max_color_distance",
        "max_height_delta",
        "max_normal_angle",
        "max_plane_residual",
        "stable_surface_ratio",
        "stable_plane_factor",
        "stable_height_factor",
        "prototype_distance_scale",
        "min_surface_membership_score",
        "min_surface_bridge_score",
        "surface_bridge_texture_score",
        "surface_bridge_shape_score",
        "surface_bridge_prototype_score",
        "min_object_membership_score",
        "min_rough_membership_score",
        "object_color_factor",
        "object_texture_delta",
        "object_roughness_delta",
        "object_texture_weight",
        "object_shape_weight",
        "object_prototype_weight",
        "object_height_weight",
        "object_bucket_weight",
        "object_normal_weight",
        "object_plane_weight",
        "rough_texture_weight",
        "rough_shape_weight",
        "rough_prototype_weight",
        "rough_height_weight",
        "rough_bucket_weight",
        "rough_normal_weight",
        "rough_plane_weight",
    ]:
        out.extend([f"--{name.replace('_', '-')}", str(getattr(args, name))])
    out.append("--enable-surface-multimodal-bridge" if args.enable_surface_multimodal_bridge else "--disable-surface-multimodal-bridge")
    return out


def grow_region_model_cpp(
    arrays: dict[str, np.ndarray],
    src: np.ndarray,
    dst: np.ndarray,
    args: argparse.Namespace,
) -> tuple[np.ndarray, list[dict[str, Any]]]:
    grower = Path(args.cpp_grower)
    if not grower.is_absolute():
        grower = Path(__file__).resolve().parents[1] / grower
    if not grower.exists():
        raise FileNotFoundError(
            f"C++ region grower not found: {grower}. Build it with scripts/build_geo_patch_cpp_smoke.sh"
        )
    args.output_dir.mkdir(parents=True, exist_ok=True)
    input_path = args.output_dir / "_cpp_region_grower_input.bin"
    output_path = args.output_dir / "_cpp_region_grower_labels.bin"
    _write_cpp_region_input(input_path, arrays, src, dst)
    command = [
        str(grower),
        "--input",
        str(input_path),
        "--output",
        str(output_path),
        *_cpp_flag_args(args),
    ]
    subprocess.run(command, check=True)
    labels = _read_cpp_region_labels(output_path)
    if len(labels) != len(arrays["xyz"]):
        raise RuntimeError(f"C++ region-grower returned {len(labels)} labels for {len(arrays['xyz'])} voxels")
    patches = summarize_patches_from_labels(arrays, labels, args)
    return labels, patches


def patch_color(patch_id: int) -> tuple[int, int, int]:
    rng = random.Random(int(patch_id) * 1000003)
    return (rng.randint(40, 245), rng.randint(40, 245), rng.randint(40, 245))


def write_outputs(
    output_dir: Path,
    arrays: dict[str, np.ndarray],
    labels: np.ndarray,
    patches: list[dict[str, Any]],
    args: argparse.Namespace,
) -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    ply_path = output_dir / "geo_patches_region_model_random_color.ply"
    jsonl_path = output_dir / "geo_patches_region_model.jsonl"
    report_path = output_dir / "geo_patch_region_model_report.json"

    with ply_path.open("w", encoding="utf-8") as f:
        f.write("ply\nformat ascii 1.0\n")
        f.write(f"element vertex {len(labels)}\n")
        f.write("property float x\nproperty float y\nproperty float z\n")
        f.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
        f.write("property uint object\nproperty uchar semantic\n")
        f.write("end_header\n")
        for xyz, patch_id in zip(arrays["xyz"], labels, strict=True):
            color = patch_color(int(patch_id))
            f.write(f"{xyz[0]:.6f} {xyz[1]:.6f} {xyz[2]:.6f} {color[0]} {color[1]} {color[2]} {int(patch_id)} 1\n")

    with jsonl_path.open("w", encoding="utf-8") as f:
        for row in patches:
            out = dict(row)
            out["semantic_label"] = out["geometry_type"]
            out["description"] = f"region-model geometry patch: {out['geometry_type']}"
            out["voxel_size"] = args.voxel_size
            f.write(json.dumps(out, ensure_ascii=False) + "\n")

    bucket_counts = Counter(ID_BUCKETS[int(bucket)] for bucket in arrays["buckets"])
    geometry_counts = Counter(str(row["geometry_type"]) for row in patches)
    report = {
        "schema": "geo-patch-region-model/v1",
        "input_ply": str(args.input_ply),
        "output_ply": str(ply_path),
        "output_jsonl": str(jsonl_path),
        "voxel_size": args.voxel_size,
        "voxel_count": int(len(labels)),
        "patch_count": int(len(patches)),
        "small_patch_count": int(sum(1 for row in patches if row["status"] == "small_patch")),
        "bucket_voxel_counts": dict(bucket_counts),
        "patch_geometry_counts": dict(geometry_counts),
        "params": vars(args),
    }
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2, default=str))
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-ply", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--voxel-size", type=float, default=0.10)
    parser.add_argument("--voxel-backend", choices=("numpy", "torch"), default="numpy")
    parser.add_argument("--binary-voxel-input", action="store_true")
    parser.add_argument("--feature-backend", choices=("cpu", "torch"), default="torch")
    parser.add_argument("--feature-radius-voxels", type=int, default=3)
    parser.add_argument("--feature-batch-size", type=int, default=8192)
    parser.add_argument("--torch-device", default="cuda:0")
    parser.add_argument("--region-grow-backend", choices=("python", "cpp"), default="python")
    parser.add_argument("--cpp-grower", type=Path, default=Path("build/geo_patch/geo_patch_region_grower"))
    parser.add_argument("--connect-radius-voxels", type=int, default=2)
    parser.add_argument("--min-edge-score", type=float, default=0.46)
    parser.add_argument("--max-color-distance", type=float, default=150.0)
    parser.add_argument("--max-height-delta", type=float, default=0.30)
    parser.add_argument("--max-normal-angle", type=float, default=120.0)
    parser.add_argument("--max-plane-residual", type=float, default=0.26)
    parser.add_argument(
        "--bucket-guard",
        choices=(
            "loose",
            "same-or-unknown",
            "no-rough-bridge",
            "same-bucket",
            "same-bucket-or-color",
            "same-bucket-or-fine-color",
        ),
        default="same-bucket-or-fine-color",
    )
    parser.add_argument("--texture-weight", type=float, default=0.12)
    parser.add_argument("--shape-weight", type=float, default=0.30)
    parser.add_argument("--height-weight", type=float, default=0.12)
    parser.add_argument("--bucket-weight", type=float, default=0.14)
    parser.add_argument("--normal-weight", type=float, default=0.12)
    parser.add_argument("--plane-weight", type=float, default=0.20)
    parser.add_argument("--color-bridge-distance-factor", type=float, default=0.70)
    parser.add_argument("--color-bridge-texture-delta", type=float, default=42.0)
    parser.add_argument("--small-patch-voxels", type=int, default=8)
    parser.add_argument("--max-points", type=int, default=None)

    parser.add_argument("--stable-surface-ratio", type=float, default=0.72)
    parser.add_argument("--stable-plane-factor", type=float, default=2.4)
    parser.add_argument("--stable-height-factor", type=float, default=2.4)
    parser.add_argument("--prototype-distance-scale", type=float, default=0.54)
    parser.add_argument("--min-surface-membership-score", type=float, default=0.50)
    parser.add_argument("--min-surface-bridge-score", type=float, default=0.56)
    parser.add_argument("--enable-surface-multimodal-bridge", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--surface-bridge-texture-score", type=float, default=0.62)
    parser.add_argument("--surface-bridge-shape-score", type=float, default=0.24)
    parser.add_argument("--surface-bridge-prototype-score", type=float, default=0.48)
    parser.add_argument("--min-object-membership-score", type=float, default=0.48)
    parser.add_argument("--min-rough-membership-score", type=float, default=0.44)
    parser.add_argument("--object-color-factor", type=float, default=1.85)
    parser.add_argument("--object-texture-delta", type=float, default=64.0)
    parser.add_argument("--object-roughness-delta", type=float, default=0.34)
    parser.add_argument("--object-texture-weight", type=float, default=0.30)
    parser.add_argument("--object-shape-weight", type=float, default=0.27)
    parser.add_argument("--object-prototype-weight", type=float, default=0.12)
    parser.add_argument("--object-height-weight", type=float, default=0.12)
    parser.add_argument("--object-bucket-weight", type=float, default=0.12)
    parser.add_argument("--object-normal-weight", type=float, default=0.06)
    parser.add_argument("--object-plane-weight", type=float, default=0.10)
    parser.add_argument("--rough-texture-weight", type=float, default=0.36)
    parser.add_argument("--rough-shape-weight", type=float, default=0.29)
    parser.add_argument("--rough-prototype-weight", type=float, default=0.18)
    parser.add_argument("--rough-height-weight", type=float, default=0.04)
    parser.add_argument("--rough-bucket-weight", type=float, default=0.14)
    parser.add_argument("--rough-normal-weight", type=float, default=0.03)
    parser.add_argument("--rough-plane-weight", type=float, default=0.03)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    voxels = read_voxels(
        args.input_ply,
        args.voxel_size,
        args.max_points,
        args.voxel_backend,
        args.torch_device,
        args.binary_voxel_input,
    )
    if args.feature_backend == "torch":
        compute_local_features_torch(voxels, args.feature_radius_voxels, args.torch_device, args.feature_batch_size)
    else:
        compute_local_features(voxels, args.feature_radius_voxels)
    for item in voxels.values():
        item["bucket"] = geometry_bucket(item)
    arrays = voxel_arrays(voxels)
    src, dst = collect_edges(
        arrays,
        args.connect_radius_voxels,
        args.min_edge_score,
        args.max_color_distance,
        args.max_height_delta,
        args.max_normal_angle,
        args.max_plane_residual,
        args.bucket_guard,
        {
            "texture": args.texture_weight,
            "shape": args.shape_weight,
            "height": args.height_weight,
            "bucket": args.bucket_weight,
            "normal": args.normal_weight,
            "plane": args.plane_weight,
        },
        args.color_bridge_distance_factor,
        args.color_bridge_texture_delta,
    )
    if args.region_grow_backend == "cpp":
        labels, patches = grow_region_model_cpp(arrays, src, dst, args)
    else:
        adjacency = build_adjacency(len(arrays["keys"]), src, dst)
        labels, patches = grow_region_model(arrays, adjacency, args)
    write_outputs(args.output_dir, arrays, labels, patches, args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
