#!/usr/bin/env python3
"""Build geometry patches with model-aware region growing.

This is the next step after build_geo_patch_graph.py.  The graph route decides
connected components from pairwise edges only, so A-B and B-C can merge A and C
even when C no longer fits the whole patch.  This script keeps the fast voxel
feature extraction and edge-admissibility pass, then grows each patch with a
dynamic patch model.

The decision is deliberately two-stage:

1. edge admissibility: local physical reachability, generated by the graph edge
   scorer.
2. patch membership: whether the candidate voxel still fits the patch model
   accumulated from already accepted voxels.
"""

from __future__ import annotations

import argparse
import json
import random
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

from build_geo_patch_demo import (
    compute_local_features,
    compute_local_features_torch,
    geometry_bucket,
    read_voxels,
)
from build_geo_patch_graph import (
    BUCKET_IDS,
    ID_BUCKETS,
    bucket_score_np,
    clamp01_np,
    collect_edges,
    voxel_arrays,
)


STABLE_SURFACE_BUCKETS = {BUCKET_IDS["horizontal"], BUCKET_IDS["vertical"]}
FINE_OBJECT_BUCKETS = {BUCKET_IDS["rough_mixed"], BUCKET_IDS["thin_linear"], BUCKET_IDS["unknown"]}


def normal_angle_deg_np(a: np.ndarray, b: np.ndarray) -> float:
    an = float(np.linalg.norm(a))
    bn = float(np.linalg.norm(b))
    if an < 1e-9 or bn < 1e-9:
        return 0.0
    cos = abs(float(np.dot(a, b) / (an * bn)))
    return float(np.degrees(np.arccos(np.clip(cos, -1.0, 1.0))))


@dataclass
class PatchModel:
    """Incremental statistics used by model-aware growth."""

    seed_index: int
    seed_bucket: int
    count: int = 0
    xyz_sum: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))
    rgb_sum: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))
    normal_sum: np.ndarray = field(default_factory=lambda: np.zeros(3, dtype=np.float64))
    roughness_sum: float = 0.0
    planarity_sum: float = 0.0
    linearity_sum: float = 0.0
    local_color_std_sum: float = 0.0
    height_range_sum: float = 0.0
    bucket_counts: Counter[int] = field(default_factory=Counter)
    xyz_min: np.ndarray = field(default_factory=lambda: np.full(3, np.inf, dtype=np.float64))
    xyz_max: np.ndarray = field(default_factory=lambda: np.full(3, -np.inf, dtype=np.float64))
    accepted_score_sum: float = 0.0
    rejected_reasons: Counter[str] = field(default_factory=Counter)

    def add(self, arrays: dict[str, np.ndarray], index: int, score: float = 1.0) -> None:
        xyz = arrays["xyz"][index].astype(np.float64, copy=False)
        rgb = arrays["rgb"][index].astype(np.float64, copy=False)
        normal = arrays["normal"][index].astype(np.float64, copy=True)
        current_normal = self.normal()
        if self.count > 0 and np.dot(normal, current_normal) < 0:
            normal = -normal
        self.count += 1
        self.xyz_sum += xyz
        self.rgb_sum += rgb
        self.normal_sum += normal
        self.roughness_sum += float(arrays["roughness"][index])
        self.planarity_sum += float(arrays["planarity"][index])
        self.linearity_sum += float(arrays["linearity"][index])
        self.local_color_std_sum += float(arrays["local_color_std"][index])
        self.height_range_sum += float(arrays["height_range"][index])
        self.bucket_counts[int(arrays["buckets"][index])] += 1
        self.xyz_min = np.minimum(self.xyz_min, xyz)
        self.xyz_max = np.maximum(self.xyz_max, xyz)
        self.accepted_score_sum += float(score)

    def mean(self, key: str) -> float:
        return float(getattr(self, f"{key}_sum") / max(float(self.count), 1.0))

    def centroid(self) -> np.ndarray:
        return self.xyz_sum / max(float(self.count), 1.0)

    def color(self) -> np.ndarray:
        return self.rgb_sum / max(float(self.count), 1.0)

    def normal(self) -> np.ndarray:
        norm = float(np.linalg.norm(self.normal_sum))
        if norm < 1e-9:
            return np.array([0.0, 0.0, 1.0], dtype=np.float64)
        return self.normal_sum / norm

    def dominant_bucket(self) -> int:
        if not self.bucket_counts:
            return self.seed_bucket
        return int(self.bucket_counts.most_common(1)[0][0])

    def dominant_ratio(self) -> float:
        if not self.bucket_counts:
            return 1.0
        return float(self.bucket_counts.most_common(1)[0][1]) / max(float(self.count), 1.0)

    def extent(self) -> np.ndarray:
        return self.xyz_max - self.xyz_min

    def mean_score(self) -> float:
        return self.accepted_score_sum / max(float(self.count), 1.0)


def build_adjacency(n: int, src: np.ndarray, dst: np.ndarray) -> list[list[int]]:
    adjacency: list[list[int]] = [[] for _ in range(n)]
    for a, b in zip(src.tolist(), dst.tolist(), strict=True):
        adjacency[a].append(b)
        adjacency[b].append(a)
    return adjacency


def membership_score(
    arrays: dict[str, np.ndarray],
    model: PatchModel,
    index: int,
    args: argparse.Namespace,
) -> tuple[bool, float, str, dict[str, float]]:
    """Return whether a voxel fits the current patch model."""

    bucket = int(arrays["buckets"][index])
    dominant = model.dominant_bucket()
    centroid = model.centroid()
    patch_normal = model.normal()
    xyz = arrays["xyz"][index].astype(np.float64, copy=False)
    rgb = arrays["rgb"][index].astype(np.float64, copy=False)
    normal = arrays["normal"][index].astype(np.float64, copy=False)

    angle = normal_angle_deg_np(patch_normal, normal)
    rgb_dist = float(np.linalg.norm(model.color() - rgb))
    dz = abs(float(xyz[2] - centroid[2]))
    plane_residual = abs(float(np.dot(xyz - centroid, patch_normal)))
    rough_delta = abs(model.mean("roughness") - float(arrays["roughness"][index]))
    planarity_delta = abs(model.mean("planarity") - float(arrays["planarity"][index]))
    linearity_delta = abs(model.mean("linearity") - float(arrays["linearity"][index]))
    color_std_delta = abs(model.mean("local_color_std") - float(arrays["local_color_std"][index]))
    height_range_delta = abs(model.mean("height_range") - float(arrays["height_range"][index]))

    scores = {
        "color": float(clamp01_np(np.asarray([1.0 - rgb_dist / max(args.max_color_distance, 1e-6)]))[0]),
        "color_texture": float(clamp01_np(np.asarray([1.0 - color_std_delta / 85.0]))[0]),
        "roughness": float(clamp01_np(np.asarray([1.0 - rough_delta / 0.24]))[0]),
        "planarity": float(clamp01_np(np.asarray([1.0 - planarity_delta / 0.50]))[0]),
        "linearity": float(clamp01_np(np.asarray([1.0 - linearity_delta / 0.50]))[0]),
        "height_range": float(clamp01_np(np.asarray([1.0 - height_range_delta / 0.28]))[0]),
        "height": float(clamp01_np(np.asarray([1.0 - dz / max(args.max_height_delta * 2.8, 1e-6)]))[0]),
        "bucket": float(bucket_score_np(np.asarray([dominant], dtype=np.int16), np.asarray([bucket], dtype=np.int16))[0]),
        "normal": float(clamp01_np(np.asarray([1.0 - angle / max(args.max_normal_angle * 1.8, 1e-6)]))[0]),
        "plane": float(clamp01_np(np.asarray([1.0 - plane_residual / max(args.max_plane_residual * 2.5, 1e-6)]))[0]),
    }
    shape_score = (
        0.38 * scores["roughness"]
        + 0.24 * scores["linearity"]
        + 0.24 * scores["planarity"]
        + 0.14 * scores["height_range"]
    )
    texture_score = 0.62 * scores["color"] + 0.38 * scores["color_texture"]

    if dominant in STABLE_SURFACE_BUCKETS and model.dominant_ratio() >= args.stable_surface_ratio:
        if bucket not in {dominant, BUCKET_IDS["unknown"]}:
            return False, 0.0, "stable_bucket_mismatch", scores
        if rgb_dist > args.max_color_distance * 1.9 and color_std_delta > 55.0:
            return False, 0.0, "stable_color_texture_jump", scores
        if angle > min(args.max_normal_angle * 1.7, 88.0):
            return False, 0.0, "stable_normal_jump", scores
        if plane_residual > args.max_plane_residual * args.stable_plane_factor:
            return False, 0.0, "stable_plane_residual", scores
        if dominant == BUCKET_IDS["horizontal"] and dz > args.max_height_delta * args.stable_height_factor:
            return False, 0.0, "stable_height_jump", scores
        total = (
            0.28 * scores["plane"]
            + 0.24 * scores["normal"]
            + 0.18 * texture_score
            + 0.12 * scores["bucket"]
            + 0.10 * shape_score
            + 0.08 * scores["height"]
        )
        threshold = args.min_surface_membership_score
    else:
        if bucket not in FINE_OBJECT_BUCKETS and dominant in FINE_OBJECT_BUCKETS:
            return False, 0.0, "fine_to_stable_bucket_block", scores
        if rgb_dist > args.max_color_distance * args.object_color_factor and color_std_delta > args.object_texture_delta:
            return False, 0.0, "object_color_texture_jump", scores
        if rough_delta > args.object_roughness_delta and color_std_delta > args.object_texture_delta:
            return False, 0.0, "object_shape_texture_jump", scores
        if dz > args.max_height_delta * args.object_height_factor and scores["color"] < 0.55:
            return False, 0.0, "object_height_jump", scores
        total = (
            args.object_texture_weight * texture_score
            + args.object_shape_weight * shape_score
            + args.object_height_weight * scores["height"]
            + args.object_bucket_weight * scores["bucket"]
            + args.object_normal_weight * scores["normal"]
            + args.object_plane_weight * scores["plane"]
        ) / max(
            args.object_texture_weight
            + args.object_shape_weight
            + args.object_height_weight
            + args.object_bucket_weight
            + args.object_normal_weight
            + args.object_plane_weight,
            1e-6,
        )
        threshold = args.min_object_membership_score

    if total < threshold:
        return False, float(total), "membership_score_low", scores
    return True, float(total), "accepted", scores


def seed_order(arrays: dict[str, np.ndarray]) -> np.ndarray:
    stable = np.isin(arrays["buckets"], [BUCKET_IDS["horizontal"], BUCKET_IDS["vertical"]])
    # Stable surfaces first lock large planes before rough objects can bridge.
    return np.lexsort(
        (
            arrays["roughness"],
            -arrays["planarity"],
            ~stable,
        )
    )


def grow_region_model(
    arrays: dict[str, np.ndarray],
    adjacency: list[list[int]],
    args: argparse.Namespace,
) -> tuple[np.ndarray, list[dict[str, Any]]]:
    n = len(arrays["keys"])
    labels = np.full(n, -1, dtype=np.int32)
    patches: list[dict[str, Any]] = []
    next_patch_id = 1

    for seed in seed_order(arrays):
        seed_i = int(seed)
        if labels[seed_i] != -1:
            continue
        model = PatchModel(seed_index=seed_i, seed_bucket=int(arrays["buckets"][seed_i]))
        model.add(arrays, seed_i, 1.0)
        labels[seed_i] = next_patch_id
        queue: deque[int] = deque([seed_i])

        while queue:
            current = queue.popleft()
            for nbr in adjacency[current]:
                if labels[nbr] != -1:
                    continue
                ok, score, reason, _scores = membership_score(arrays, model, int(nbr), args)
                if not ok:
                    model.rejected_reasons[reason] += 1
                    continue
                labels[nbr] = next_patch_id
                model.add(arrays, int(nbr), score)
                queue.append(int(nbr))

        dominant_bucket = model.dominant_bucket()
        geometry_type = ID_BUCKETS[dominant_bucket] if model.dominant_ratio() >= 0.65 else "mixed"
        patches.append(
            {
                "patch_id": next_patch_id,
                "voxel_count": int(model.count),
                "status": "small_patch" if model.count < args.small_patch_voxels else "geo_patch",
                "geometry_type": geometry_type,
                "bucket_counts": {ID_BUCKETS[int(k)]: int(v) for k, v in model.bucket_counts.items()},
                "centroid": model.centroid().astype(float).tolist(),
                "bbox_3d": {"min": model.xyz_min.astype(float).tolist(), "max": model.xyz_max.astype(float).tolist()},
                "extent": model.extent().astype(float).tolist(),
                "mean_rgb": model.color().astype(float).tolist(),
                "mean_normal": model.normal().astype(float).tolist(),
                "mean_membership_score": float(model.mean_score()),
                "rejected_reasons_top": dict(model.rejected_reasons.most_common(8)),
            }
        )
        next_patch_id += 1

    if np.any(labels < 0):
        raise RuntimeError(f"internal error: unassigned voxels remain: {int(np.sum(labels < 0))}")
    return labels, patches


def patch_color(patch_id: int) -> tuple[int, int, int]:
    rng = random.Random(int(patch_id) * 1000003)
    return (rng.randint(40, 245), rng.randint(40, 245), rng.randint(40, 245))


def write_outputs(
    output_dir: Path,
    arrays: dict[str, np.ndarray],
    labels: np.ndarray,
    patches: list[dict[str, Any]],
    args: argparse.Namespace,
) -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    ply_path = output_dir / "geo_patches_region_model_random_color.ply"
    jsonl_path = output_dir / "geo_patches_region_model.jsonl"
    report_path = output_dir / "geo_patch_region_model_report.json"

    with ply_path.open("w", encoding="utf-8") as f:
        f.write("ply\nformat ascii 1.0\n")
        f.write(f"element vertex {len(labels)}\n")
        f.write("property float x\nproperty float y\nproperty float z\n")
        f.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
        f.write("property uint object\nproperty uchar semantic\n")
        f.write("end_header\n")
        for xyz, patch_id in zip(arrays["xyz"], labels, strict=True):
            color = patch_color(int(patch_id))
            f.write(f"{xyz[0]:.6f} {xyz[1]:.6f} {xyz[2]:.6f} {color[0]} {color[1]} {color[2]} {int(patch_id)} 1\n")

    with jsonl_path.open("w", encoding="utf-8") as f:
        for row in patches:
            out = dict(row)
            out["semantic_label"] = out["geometry_type"]
            out["description"] = f"region-model geometry patch: {out['geometry_type']}"
            out["voxel_size"] = args.voxel_size
            f.write(json.dumps(out, ensure_ascii=False) + "\n")

    bucket_counts = Counter(ID_BUCKETS[int(bucket)] for bucket in arrays["buckets"])
    geometry_counts = Counter(str(row["geometry_type"]) for row in patches)
    report = {
        "schema": "geo-patch-region-model/v1",
        "input_ply": str(args.input_ply),
        "output_ply": str(ply_path),
        "output_jsonl": str(jsonl_path),
        "voxel_size": args.voxel_size,
        "voxel_count": int(len(labels)),
        "patch_count": int(len(patches)),
        "small_patch_count": int(sum(1 for row in patches if row["status"] == "small_patch")),
        "bucket_voxel_counts": dict(bucket_counts),
        "patch_geometry_counts": dict(geometry_counts),
        "params": vars(args),
    }
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2, default=str))
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-ply", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--voxel-size", type=float, default=0.10)
    parser.add_argument("--voxel-backend", choices=("numpy", "torch"), default="numpy")
    parser.add_argument("--binary-voxel-input", action="store_true")
    parser.add_argument("--feature-backend", choices=("cpu", "torch"), default="torch")
    parser.add_argument("--feature-radius-voxels", type=int, default=3)
    parser.add_argument("--feature-batch-size", type=int, default=8192)
    parser.add_argument("--torch-device", default="cuda:0")
    parser.add_argument("--connect-radius-voxels", type=int, default=2)
    parser.add_argument("--min-edge-score", type=float, default=0.46)
    parser.add_argument("--max-color-distance", type=float, default=150.0)
    parser.add_argument("--max-height-delta", type=float, default=0.30)
    parser.add_argument("--max-normal-angle", type=float, default=120.0)
    parser.add_argument("--max-plane-residual", type=float, default=0.26)
    parser.add_argument(
        "--bucket-guard",
        choices=(
            "loose",
            "same-or-unknown",
            "no-rough-bridge",
            "same-bucket",
            "same-bucket-or-color",
            "same-bucket-or-fine-color",
        ),
        default="same-bucket-or-fine-color",
    )
    parser.add_argument("--texture-weight", type=float, default=0.12)
    parser.add_argument("--shape-weight", type=float, default=0.30)
    parser.add_argument("--height-weight", type=float, default=0.12)
    parser.add_argument("--bucket-weight", type=float, default=0.14)
    parser.add_argument("--normal-weight", type=float, default=0.12)
    parser.add_argument("--plane-weight", type=float, default=0.20)
    parser.add_argument("--color-bridge-distance-factor", type=float, default=0.70)
    parser.add_argument("--color-bridge-texture-delta", type=float, default=42.0)
    parser.add_argument("--small-patch-voxels", type=int, default=8)
    parser.add_argument("--max-points", type=int, default=None)

    parser.add_argument("--stable-surface-ratio", type=float, default=0.72)
    parser.add_argument("--stable-plane-factor", type=float, default=2.4)
    parser.add_argument("--stable-height-factor", type=float, default=2.4)
    parser.add_argument("--min-surface-membership-score", type=float, default=0.50)
    parser.add_argument("--min-object-membership-score", type=float, default=0.48)
    parser.add_argument("--object-color-factor", type=float, default=1.85)
    parser.add_argument("--object-texture-delta", type=float, default=64.0)
    parser.add_argument("--object-roughness-delta", type=float, default=0.34)
    parser.add_argument("--object-height-factor", type=float, default=3.5)
    parser.add_argument("--object-texture-weight", type=float, default=0.30)
    parser.add_argument("--object-shape-weight", type=float, default=0.30)
    parser.add_argument("--object-height-weight", type=float, default=0.12)
    parser.add_argument("--object-bucket-weight", type=float, default=0.12)
    parser.add_argument("--object-normal-weight", type=float, default=0.06)
    parser.add_argument("--object-plane-weight", type=float, default=0.10)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    voxels = read_voxels(
        args.input_ply,
        args.voxel_size,
        args.max_points,
        args.voxel_backend,
        args.torch_device,
        args.binary_voxel_input,
    )
    if args.feature_backend == "torch":
        compute_local_features_torch(voxels, args.feature_radius_voxels, args.torch_device, args.feature_batch_size)
    else:
        compute_local_features(voxels, args.feature_radius_voxels)
    for item in voxels.values():
        item["bucket"] = geometry_bucket(item)
    arrays = voxel_arrays(voxels)
    src, dst = collect_edges(
        arrays,
        args.connect_radius_voxels,
        args.min_edge_score,
        args.max_color_distance,
        args.max_height_delta,
        args.max_normal_angle,
        args.max_plane_residual,
        args.bucket_guard,
        {
            "texture": args.texture_weight,
            "shape": args.shape_weight,
            "height": args.height_weight,
            "bucket": args.bucket_weight,
            "normal": args.normal_weight,
            "plane": args.plane_weight,
        },
        args.color_bridge_distance_factor,
        args.color_bridge_texture_delta,
    )
    adjacency = build_adjacency(len(arrays["keys"]), src, dst)
    labels, patches = grow_region_model(arrays, adjacency, args)
    write_outputs(args.output_dir, arrays, labels, patches, args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
