#!/usr/bin/env python3
"""Compare the current dense Patch/Object and semantic-guard baselines.

This script is intentionally report-driven: it reads small JSON reports that
were already generated by the dense pipeline, instead of re-parsing large PLYs.
Use it as a stable operator checkpoint before promoting a new object/semantic
variant.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BASE = (
    REPO_ROOT
    / "server_parking_priority_s10"
    / "geo_patch_las_opt_cpp_v2_voxel003_r4_4090d_20260623"
)


def resolve_path(path: Path) -> Path:
    if path.is_absolute():
        return path
    cwd_path = Path.cwd() / path
    if cwd_path.exists():
        return cwd_path
    return REPO_ROOT / path


def read_json(path: Path) -> dict[str, Any]:
    path = resolve_path(path)
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def get_nested(data: dict[str, Any], *keys: str, default: Any = None) -> Any:
    cur: Any = data
    for key in keys:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def as_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def as_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def delta(candidate: int | float, baseline: int | float) -> int | float:
    return candidate - baseline


def compare_object_refinement(base: Path) -> dict[str, Any]:
    v7_root = base / "dense_patch_object_refinement_v7_r4_attach_v4_20260624_170126"
    v8_root = base / "dense_patch_object_refinement_v8_tiny_attach_20260624_170619"
    candidate_rel = "object_merge_candidates_v7_structural_multimaterial/geo_patch_object_merge_candidates_report.json"
    object_rel = "objects_v7_structural_multimaterial/geo_patch_objects_v7_structural_multimaterial_report.json"
    overlap_rel = "objects_v7_structural_multimaterial/voxel_overlap_020_report.json"

    v7_candidates = read_json(v7_root / candidate_rel)
    v8_candidates = read_json(v8_root / candidate_rel)
    v7_objects = read_json(v7_root / object_rel)
    v8_objects = read_json(v8_root / object_rel)
    v7_overlap = read_json(v7_root / overlap_rel)
    v8_overlap = read_json(v8_root / overlap_rel)

    rows = {
        "v7": {
            "candidate_count": as_int(v7_candidates.get("candidate_count")),
            "same_material_candidates": as_int(get_nested(v7_candidates, "merge_class_counts", "same_material")),
            "structural_multimaterial_candidates": as_int(
                get_nested(v7_candidates, "merge_class_counts", "structural_multimaterial")
            ),
            "big_mixed_attachment_count": as_int(v7_candidates.get("big_mixed_attachment_count")),
            "accepted_candidate_rows": as_int(v7_objects.get("accepted_candidate_rows")),
            "output_object_count": as_int(v7_objects.get("output_object_count")),
            "mixed_object_voxel_ratio_020": as_float(v7_overlap.get("mixed_object_voxel_ratio")),
            "object_count_in_overlap_preview": as_int(v7_overlap.get("object_count")),
        },
        "v8": {
            "candidate_count": as_int(v8_candidates.get("candidate_count")),
            "same_material_candidates": as_int(get_nested(v8_candidates, "merge_class_counts", "same_material")),
            "structural_multimaterial_candidates": as_int(
                get_nested(v8_candidates, "merge_class_counts", "structural_multimaterial")
            ),
            "big_mixed_attachment_count": as_int(v8_candidates.get("big_mixed_attachment_count")),
            "accepted_candidate_rows": as_int(v8_objects.get("accepted_candidate_rows")),
            "output_object_count": as_int(v8_objects.get("output_object_count")),
            "mixed_object_voxel_ratio_020": as_float(v8_overlap.get("mixed_object_voxel_ratio")),
            "object_count_in_overlap_preview": as_int(v8_overlap.get("object_count")),
        },
    }
    rows["delta_v8_minus_v7"] = {
        key: delta(rows["v8"][key], rows["v7"][key])
        for key in rows["v8"]
        if isinstance(rows["v8"][key], (int, float)) and isinstance(rows["v7"].get(key), (int, float))
    }
    return {
        "schema": "dense-object-refinement-compare/v1",
        "baseline": "v7_r4_attach_v4",
        "candidate": "v8_tiny_attach",
        "metrics": rows,
        "interpretation": (
            "v8 greatly increases merge candidate recall and accepted merges. "
            "The coarse 0.20m mixed-object voxel ratio is slightly lower than v7, "
            "so v8 is a viable visual-QA candidate rather than an automatic semantic baseline."
        ),
    }


def compare_surface_guard(base: Path) -> dict[str, Any]:
    v9 = read_json(base / "objects_v9_teacher_v20_semantic/objects_v9_teacher_v20_semantic_report.json")
    v17 = read_json(
        base
        / "objects_v17_teacher_v20_surface_preserve_guard"
        / "objects_v17_teacher_v20_surface_preserve_guard_report.json"
    )

    v9_points = {str(k): as_int(v) for k, v in (v9.get("label_point_counts") or {}).items()}
    v17_points = {str(k): as_int(v) for k, v in (v17.get("label_point_counts") or {}).items()}
    keys = sorted(set(v9_points) | set(v17_points))
    delta_points = {key: v17_points.get(key, 0) - v9_points.get(key, 0) for key in keys}
    return {
        "schema": "surface-guard-compare/v1",
        "baseline": "objects_v9_teacher_v20_semantic",
        "candidate": "objects_v17_teacher_v20_surface_preserve_guard",
        "label_point_counts": {
            "v9": v9_points,
            "v17": v17_points,
            "delta_v17_minus_v9": delta_points,
        },
        "unknown_point_delta_v17_minus_v9": int(delta_points.get("unknown", 0)),
        "object_count": {
            "v9": as_int(v9.get("object_count")),
            "v17": as_int(v17.get("object_count")),
        },
        "changed_object_count": as_int(v17.get("changed_object_count")),
        "interpretation": (
            "v17 confirms the unknown spike in v15/v16 was caused by guard-policy demotion. "
            "Preserving floor/wall labels keeps point counts aligned with v9 while still documenting guard status."
        ),
    }


def build_report(base: Path) -> dict[str, Any]:
    base = resolve_path(base)
    return {
        "schema": "current-dense-mainline-qa/v1",
        "base_dir": str(base),
        "object_refinement": compare_object_refinement(base),
        "surface_guard": compare_surface_guard(base),
        "promotion_gates": [
            "Object ownership must remain exclusive.",
            "Mixed-object coarse voxel ratio must not regress while fragmentation decreases.",
            "Surface guard must not demote floor/wall to unknown solely due to missing teacher evidence.",
            "Semantic variants remain QA references until visual inspection passes.",
        ],
    }


def format_md(report: dict[str, Any]) -> str:
    obj = report["object_refinement"]["metrics"]
    surf = report["surface_guard"]["label_point_counts"]
    lines = [
        "# Current Dense Mainline QA",
        "",
        f"Base: `{report['base_dir']}`",
        "",
        "## Object Refinement",
        "",
        "| metric | v7 | v8 | delta |",
        "|---|---:|---:|---:|",
    ]
    for key in [
        "candidate_count",
        "accepted_candidate_rows",
        "output_object_count",
        "mixed_object_voxel_ratio_020",
        "object_count_in_overlap_preview",
    ]:
        lines.append(f"| {key} | {obj['v7'][key]} | {obj['v8'][key]} | {obj['delta_v8_minus_v7'][key]} |")

    lines.extend(
        [
            "",
            "## Surface Guard",
            "",
            "| label | v9 points | v17 points | delta |",
            "|---|---:|---:|---:|",
        ]
    )
    for key in sorted(set(surf["v9"]) | set(surf["v17"])):
        lines.append(
            f"| {key} | {surf['v9'].get(key, 0)} | {surf['v17'].get(key, 0)} | "
            f"{surf['delta_v17_minus_v9'].get(key, 0)} |"
        )
    lines.append("")
    lines.append(f"Unknown point delta v17-v9: `{report['surface_guard']['unknown_point_delta_v17_minus_v9']}`")

    lines.extend(["", "## Gates", ""])
    lines.extend(f"- {item}" for item in report["promotion_gates"])
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-dir", type=Path, default=DEFAULT_BASE)
    parser.add_argument("--output-json", type=Path)
    parser.add_argument("--output-md", type=Path)
    args = parser.parse_args()

    report = build_report(args.base_dir)
    if args.output_json:
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        args.output_json.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.output_md:
        args.output_md.parent.mkdir(parents=True, exist_ok=True)
        args.output_md.write_text(format_md(report), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
