#!/usr/bin/env python3
"""Compare semantic PLY/Object viewer QA reports.

This is a route-level comparison helper for outputs generated by
``qa_viewer_candidate.py``.  It deliberately compares cheap, reproducible
viewer artifact metrics instead of relying on visual memory:

- point/object label distribution
- warning/error state
- status distribution
- large fine-object risk objects
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def parse_named_report(raw: str) -> tuple[str, Path]:
    if "=" not in raw:
        path = Path(raw)
        return path.parent.name or path.stem, path
    name, path = raw.split("=", 1)
    name = name.strip()
    if not name:
        raise ValueError(f"missing report name in {raw!r}")
    return name, Path(path)


def as_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def as_counter(value: Any) -> dict[str, int]:
    if not isinstance(value, dict):
        return {}
    return {str(k): as_int(v) for k, v in value.items()}


def get_in(data: dict[str, Any], path: list[str], default: Any = None) -> Any:
    current: Any = data
    for key in path:
        if not isinstance(current, dict):
            return default
        current = current.get(key)
    return default if current is None else current


def collect_label_keys(rows: dict[str, dict[str, Any]]) -> list[str]:
    keys: set[str] = set()
    for row in rows.values():
        keys.update(row["label_point_counts"])
        keys.update(row["label_object_counts"])
    preferred = ["ground", "floor", "wall", "ceiling", "car", "railing", "grass", "unknown", "other"]
    ordered = [key for key in preferred if key in keys]
    ordered.extend(sorted(keys - set(ordered)))
    return ordered


def summarize_report(path: Path) -> dict[str, Any]:
    report = read_json(path)
    objects = get_in(report, ["objects"], {})
    ply = get_in(report, ["ply"], {})
    large_fine = get_in(objects, ["large_fine_objects"], [])
    if not isinstance(large_fine, list):
        large_fine = []
    return {
        "path": str(path),
        "status": str(report.get("status") or "unknown"),
        "warnings": list(report.get("warnings") or []),
        "errors": list(report.get("errors") or []),
        "vertices": as_int(ply.get("data_rows", ply.get("vertex_count"))),
        "object_count": as_int(objects.get("object_count")),
        "label_point_counts": as_counter(objects.get("label_point_counts")),
        "label_object_counts": as_counter(objects.get("label_object_counts")),
        "status_counts": as_counter(objects.get("status_counts")),
        "large_fine_object_count": len(large_fine),
        "large_fine_object_points": sum(as_int(row.get("point_count")) for row in large_fine if isinstance(row, dict)),
        "large_fine_object_ids": [
            as_int(row.get("object_id"))
            for row in large_fine
            if isinstance(row, dict) and row.get("object_id") is not None
        ],
    }


def delta_counter(counter: dict[str, int], baseline: dict[str, int], keys: list[str]) -> dict[str, int]:
    return {key: as_int(counter.get(key, 0)) - as_int(baseline.get(key, 0)) for key in keys}


def build_comparison(named_reports: list[tuple[str, Path]]) -> dict[str, Any]:
    versions = {name: summarize_report(path) for name, path in named_reports}
    baseline_name = named_reports[0][0] if named_reports else ""
    baseline = versions.get(baseline_name, {})
    label_keys = collect_label_keys(versions)
    status_keys = sorted({key for row in versions.values() for key in row["status_counts"]})

    deltas: dict[str, dict[str, Any]] = {}
    for name, row in versions.items():
        deltas[name] = {
            "vertices": as_int(row.get("vertices")) - as_int(baseline.get("vertices")),
            "object_count": as_int(row.get("object_count")) - as_int(baseline.get("object_count")),
            "large_fine_object_count": as_int(row.get("large_fine_object_count"))
            - as_int(baseline.get("large_fine_object_count")),
            "large_fine_object_points": as_int(row.get("large_fine_object_points"))
            - as_int(baseline.get("large_fine_object_points")),
            "label_point_counts": delta_counter(
                row["label_point_counts"], baseline.get("label_point_counts", {}), label_keys
            ),
            "label_object_counts": delta_counter(
                row["label_object_counts"], baseline.get("label_object_counts", {}), label_keys
            ),
            "status_counts": delta_counter(row["status_counts"], baseline.get("status_counts", {}), status_keys),
        }

    return {
        "baseline": baseline_name,
        "label_keys": label_keys,
        "status_keys": status_keys,
        "versions": versions,
        "deltas_from_baseline": deltas,
    }


def format_counter(counter: dict[str, int], keys: list[str]) -> str:
    return ", ".join(f"{key}={as_int(counter.get(key, 0)):,}" for key in keys if as_int(counter.get(key, 0)))


def format_delta_counter(counter: dict[str, int], keys: list[str]) -> str:
    return ", ".join(f"{key}={as_int(counter.get(key, 0)):+,}" for key in keys if as_int(counter.get(key, 0)))


def markdown_report(comparison: dict[str, Any]) -> str:
    versions = comparison["versions"]
    deltas = comparison["deltas_from_baseline"]
    label_keys = comparison["label_keys"]
    lines = [
        "# Viewer Candidate QA Comparison",
        "",
        f"Baseline: `{comparison['baseline']}`",
        "",
        "| version | status | vertices | objects | warnings | errors | large fine objects | large fine points |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name, row in versions.items():
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{name}`",
                    f"`{row['status']}`",
                    f"{row['vertices']:,}",
                    f"{row['object_count']:,}",
                    f"{len(row['warnings']):,}",
                    f"{len(row['errors']):,}",
                    f"{row['large_fine_object_count']:,}",
                    f"{row['large_fine_object_points']:,}",
                ]
            )
            + " |"
        )

    lines.extend(["", "## Label Point Counts", ""])
    lines.append("| version | " + " | ".join(label_keys) + " |")
    lines.append("| --- | " + " | ".join(["---:" for _ in label_keys]) + " |")
    for name, row in versions.items():
        values = [f"`{name}`", *[f"{as_int(row['label_point_counts'].get(key, 0)):,}" for key in label_keys]]
        lines.append("| " + " | ".join(values) + " |")

    lines.extend(["", "## Delta From Baseline", ""])
    for name, row in deltas.items():
        lines.append(f"### `{name}`")
        lines.append("")
        lines.append(f"- vertices: {row['vertices']:+,}")
        lines.append(f"- objects: {row['object_count']:+,}")
        lines.append(f"- large fine objects: {row['large_fine_object_count']:+,}")
        lines.append(f"- large fine points: {row['large_fine_object_points']:+,}")
        label_delta = format_delta_counter(row["label_point_counts"], label_keys)
        lines.append(f"- label point delta: {label_delta or '0'}")
        status_delta = format_delta_counter(row["status_counts"], comparison["status_keys"])
        lines.append(f"- status delta: {status_delta or '0'}")
        lines.append("")

    lines.extend(["## Warnings And Errors", ""])
    for name, row in versions.items():
        lines.append(f"### `{name}`")
        lines.append("")
        lines.append("- warnings: " + ("; ".join(row["warnings"]) if row["warnings"] else "none"))
        lines.append("- errors: " + ("; ".join(row["errors"]) if row["errors"] else "none"))
        if row["large_fine_object_ids"]:
            lines.append("- large fine object ids: " + ", ".join(str(v) for v in row["large_fine_object_ids"]))
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        action="append",
        required=True,
        help="QA report path, optionally named as name=/path/viewer_candidate_qa.json. First report is baseline.",
    )
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--output-md", type=Path, required=True)
    args = parser.parse_args()

    named_reports = [parse_named_report(raw) for raw in args.report]
    comparison = build_comparison(named_reports)
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(comparison, ensure_ascii=False, indent=2), encoding="utf-8")
    args.output_md.parent.mkdir(parents=True, exist_ok=True)
    args.output_md.write_text(markdown_report(comparison), encoding="utf-8")
    print(
        json.dumps(
            {
                "baseline": comparison["baseline"],
                "versions": list(comparison["versions"]),
                "output_json": str(args.output_json),
                "output_md": str(args.output_md),
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
